version: '3.8'

volumes:
  postgres_data:

networks:
  web_net:

services:

  web:
    build: .
    container_name: techtask.web
    ports:
      - "5001:5000"
    env_file:
      - ./.env.dev
    networks:
      - web_net
    volumes:
      - ./backend/:/var/www/app
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - web_net
    container_name: techtask.postgres
    environment:
      - POSTGRES_USER=flask_user
      - POSTGRES_PASSWORD=flask_pass
      - POSTGRES_DB=flask_dev_db

  test_db:
    image: postgres:16.0-alpine
    ports:
      - "5432"
    networks:
      - web_net
    container_name: techtask.test.postgres
    environment:
      - POSTGRES_USER=flask_user
      - POSTGRES_PASSWORD=flask_pass
      - POSTGRES_DB=flask_dev_db
